from __future__ import annotations

from pathlib import Path

from profiler.models.profile import ColumnProfile, DatasetProfile
from profiler.utils.size_formatter import SizeFormatter


class MarkdownExporter:
    """Exports a DatasetProfile to a Markdown report file."""

    @staticmethod
    def export(profile: DatasetProfile, output_path: Path) -> Path:
        """
        Writes a full Markdown report.

        Parameters
        ----------
        profile : DatasetProfile
            The profile to render.
        output_path : Path
            Destination .md file.

        Returns
        -------
        Path
            Path to the written file.
        """
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        lines: list[str] = []
        a = lines.append

        a(f"# DataProfiler Report — {profile.dataset_name}\n")

        # Overview
        a("## Overview\n")
        a(f"| Property | Value |")
        a(f"|---|---|")
        a(f"| Dataset | {profile.dataset_name} |")
        a(f"| Rows | {profile.rows:,} |")
        a(f"| Columns | {profile.columns} |")
        a(f"| Memory Usage | {SizeFormatter.format(profile.memory_usage)} |")
        a(f"| Duplicate Rows | {profile.duplicate_rows} |")
        a("")

        # Health score
        if profile.health_score:
            hs = profile.health_score
            a("## Health Score\n")
            a(f"**Score:** {hs.score} / 100  **Grade:** {hs.grade}\n")

        # Completeness
        c = profile.completeness
        a("## Dataset Completeness\n")
        a(f"| Metric | Value |")
        a(f"|---|---|")
        a(f"| Total Cells | {c.total_cells:,} |")
        a(f"| Filled Cells | {c.filled_cells:,} |")
        a(f"| Missing Cells | {c.missing_cells:,} |")
        a(f"| Completeness | {c.completeness_percentage:.2f}% |")
        a("")

        # Column summary
        a("## Column Summary\n")
        a("| # | Column | Type | Nullable | Missing | Unique | Memory |")
        a("|---|---|---|---|---|---|---|")
        for i, col in enumerate(profile.column_profiles, 1):
            missing = f"{col.missing_count} ({col.missing_percentage:.1f}%)"
            unique = f"{col.unique_count} ({col.unique_percentage:.1f}%)"
            nullable = "Yes" if col.nullable else "No"
            a(f"| {i} | {col.name} | {col.dtype} | {nullable} | {missing} | {unique} | {SizeFormatter.format(col.memory_usage)} |")
        a("")

        # Column statistics
        has_stats = any(
            col.numeric_stats or col.categorical_stats
            or col.datetime_stats or col.boolean_stats
            for col in profile.column_profiles
        )

        if has_stats:
            a("## Column Statistics\n")
            for col in profile.column_profiles:
                MarkdownExporter._col_stats(col, lines)

        # Data quality
        if profile.quality_report:
            qr = profile.quality_report
            a("## Data Quality\n")

            if qr.constant_columns:
                a(f"\n**Constant Columns:** {', '.join(qr.constant_columns)}")
            if qr.high_cardinality_columns:
                a(f"\n**High Cardinality Columns:** {', '.join(qr.high_cardinality_columns)}")
            if qr.outlier_columns:
                a(f"\n**Columns with Outliers:** {', '.join(qr.outlier_columns)}")

            if qr.warnings:
                a("\n### Warnings\n")
                for w in qr.warnings:
                    a(f"- ⚠ {w}")

            if qr.recommendations:
                a("\n### Recommendations\n")
                for r in qr.recommendations:
                    a(f"- → {r}")
            a("")

        a("---")
        a("*Generated by DataProfiler*")

        output_path.write_text("\n".join(lines), encoding="utf-8")
        return output_path

    @staticmethod
    def _col_stats(col: ColumnProfile, lines: list[str]) -> None:
        a = lines.append
        if col.numeric_stats:
            ns = col.numeric_stats
            a(f"### {col.name} ({col.dtype})\n")
            a(f"| Statistic | Value |")
            a(f"|---|---|")
            a(f"| Mean | {ns.mean} |")
            a(f"| Median | {ns.median} |")
            a(f"| Mode | {ns.mode if ns.mode is not None else 'N/A'} |")
            a(f"| Std Dev | {ns.std} |")
            a(f"| Min | {ns.minimum} |")
            a(f"| Max | {ns.maximum} |")
            a(f"| Q1 | {ns.q1} |")
            a(f"| Q3 | {ns.q3} |")
            a(f"| IQR | {ns.iqr} |")
            a(f"| Skewness | {ns.skewness} |")
            a(f"| Kurtosis | {ns.kurtosis} |")
            a("")

        elif col.categorical_stats:
            cs = col.categorical_stats
            a(f"### {col.name} ({col.dtype})\n")
            a(f"| Statistic | Value |")
            a(f"|---|---|")
            a(f"| Distinct Values | {cs.distinct_count} |")
            a(f"| Most Frequent | {cs.most_frequent} ({cs.most_frequent_pct}%) |")
            a(f"| Least Frequent | {cs.least_frequent} ({cs.least_frequent_pct}%) |")
            a("")

        elif col.datetime_stats:
            ds = col.datetime_stats
            a(f"### {col.name} ({col.dtype})\n")
            a(f"| Statistic | Value |")
            a(f"|---|---|")
            a(f"| Earliest | {ds.earliest} |")
            a(f"| Latest | {ds.latest} |")
            a(f"| Range (days) | {ds.date_range_days} |")
            a("")

        elif col.boolean_stats:
            bs = col.boolean_stats
            a(f"### {col.name} ({col.dtype})\n")
            a(f"| Statistic | Value |")
            a(f"|---|---|")
            a(f"| True | {bs.true_count} ({bs.true_pct}%) |")
            a(f"| False | {bs.false_count} ({bs.false_pct}%) |")
            a(f"| Null | {bs.null_count} |")
            a("")
